use_frameworks!

platform :ios, '9.0'

target 'QMLibraryPodManger_Example' do
  pod 'QMLibraryPodManger', :path => '../'

  target 'QMLibraryPodManger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
